name: My first ci

on:
  push:
    branches: [main]
jobs:
  java-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/chatverse

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: ./mvnw test

jobs:
  python-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: agent_framework/
    
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.12'

      - run: uv sync
      - run: uv run pytest